=== opengeospatial/IndoorGML-SWG/IndoorGML2/IndoorGML2_metanorma/Part II/JSON/indoorjson2.core.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://www.indoorgml.org/schemas/indoorjson/0.1/indoorjson2.core.schema.json",
  "title": "IndoorJSON for IndoorGML 2.0 core part",
  "description": "IndoorJSON",
  "$defs": {

    "IndoorFeatures": {
      "$anchor": "IndoorFeatures",
      "type": "object",
      "properties": {
        "id": { "type": "string" },
        "featureType": { "enum": ["IndoorFeatures"] },
        "layers": {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#/$defs/ThematicLayer" },
          "uniqueItems": true
        },
        "layerConnections": {
          "type": "array",
          "items": { "$ref": "#/$defs/InterLayerConnection" },
          "uniqueItems": true
        }
      },
      "required": ["featureType","layers"]
    },

    "ThematicLayer": {
      "$anchor": "ThematicLayer",
      "type": "object",
      "properties": {
        "id": { "type": "string" },
        "featureType": { "enum": ["ThematicLayer"] },
        "semanticExtension": { "type": "boolean" },
        "theme": { "enum": ["Virtual", "Physical", "Tags", "Unknown"] },
        "primalSpace": { "$ref": "#/$defs/PrimalSpaceLayer" },
        "dualSpace": { "$ref": "#/$defs/DualSpaceLayer" }
      },
      "required": ["id","featureType","semanticExtension","theme"]
    },

    "PrimalSpaceLayer": {
      "$anchor": "PrimalSpaceLayer",
      "type": "object",
      "properties": {
        "id": { "type": "string" },
        "featureType": { "enum": ["PrimalSpaceLayer"] },
        "creationDatetime": { "type": "string", "format": "date-time" },
        "terminationDatetime": { "type": "string", "format": "date-time" },
        "cellSpaceMember": {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#/$defs/CellSpace" },
          "uniqueItems": true
        },
        "cellBoundaryMember": {
          "type": "array",
          "items": { "$ref": "#/$defs/CellBoundary" },
          "uniqueItems": true
        }
      },
      "required": ["featureType","cellSpaceMember"]
    },

    "CellSpace": {
      "$anchor": "CellSpace",
      "type": "object",
      "properties": {
        "id": { "type": "string" },
        "featureType": { "enum": ["CellSpace"] },
        "level": { "type": "string" },
        "poi": { "type":  "boolean" },
        "duality" : { "type": "string", "format": "uri-reference"},
        "cellSpaceGeom" : {
          "type": "object",
          "properties": {
            "geometry2D": { "$ref": "geometry-object.json#/$defs/Polygon" },
            "geometry3D": { "$ref": "geometry-object.json#/$defs/Polyhedron" }
          }
        },
        "boundedBy": {
          "type": "array",
          "items": { "type": "string" },
          "uniqueItems": true
        },
        "externalReference": { "$ref": "#/$defs/ExternalReference" }
      },
      "required": ["id","featureType","poi"]
    },

    "CellBoundary": {
      "$anchor": "CellBoundary",
      "type": "object",
      "properties": {
        "id": { "type": "string" },
        "featureType": { "enum": ["CellBoundary"] },
        "isVirtual": { "type":  "boolean" },
        "duality" : { "type": "string", "format": "uri-reference"},
        "cellBoundaryGeom" : {
          "type": "object",
          "properties": {
            "geometry2D": { "$ref": "geometry-object.json#/$defs/LineString" },
            "geometry3D": { "$ref": "geometry-object.json#/$defs/Polygon" }
          }
        },
        "externalReference": { "$ref": "#/$defs/ExternalReference" }
      },
      "required": ["id","featureType","isVirtual"]
    },

    "DualSpaceLayer": {
      "$anchor": "DualSpaceLayer",
      "type": "object",
      "properties": {
        "id": { "type": "string" },
        "featureType": { "enum": ["DualSpaceLayer"] },
        "creationDatetime": { "type": "string", "format": "date-time" },
        "terminationDatetime": { "type": "string", "format": "date-time" },
        "isLogical": { "type": "boolean" },
        "isDirected": { "type": "boolean" },
        "nodeMember": {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#/$defs/Node" },
          "uniqueItems": true
        },
        "edgeMember": {
          "type": "array",
          "items": { "$ref": "#/$defs/Edge" },
          "uniqueItems": true
        }
      },
      "required": ["id","featureType","isLogical","isDirected","nodeMember"]
    },

    "Node": {
      "$anchor": "Node",
      "type": "object",
      "properties": {
        "id": { "type": "string" },
        "featureType": { "enum": ["Node"] },
        "duality" : { "type": "string", "format": "uri-reference" },
        "geometry" : { "$ref": "geometry-object.json#/$defs/Point" },
        "connects" : {
          "type": "array",
          "items": { "type": "string", "format": "uri-reference" },
          "uniqueItems": true
        }
      },
      "required": ["id","featureType","duality"]
    },

    "Edge": {
      "$anchor": "Edge",
      "type": "object",
      "properties": {
        "id": { "type": "string" },
        "featureType": { "enum": ["Edge"] },
        "duality" : { "type": "string", "format": "uri-reference" },
        "weight" : { "type": "number" },
        "geometry" : { "$ref": "geometry-object.json#/$defs/LineString" },
        "connects" : {
          "type": "array",
          "items": { "type": "string", "format": "uri-reference" },
          "minItems": 2,
          "maximum": 2,
          "uniqueItems": true
        }
      },
      "required": ["id","featureType","weight","connects"]
    },

    "InterLayerConnection": {
      "$anchor": "InterLayerConnection",
      "type": "object",
      "properties": {
        "id": { "type": "string" },
        "featureType": { "enum": ["InterLayerConnection"] },
        "connectedLayers": {
          "type": "array",
          "items": { "type": "string", "format": "uri-reference" },
          "minItems": 2,
          "maximum": 2,
          "uniqueItems": true
        },
        "connectedNodes" : {
          "type": "array",
          "items": { "type": "string", "format": "uri-reference" },
          "minItems": 2,
          "maximum": 2,
          "uniqueItems": true
        },
        "connectedCells" : {
          "type": "array",
          "items": { "type": "string", "format": "uri-reference" },
          "minItems": 2,
          "maximum": 2,
          "uniqueItems": true
        },
        "typeOfTopoExpression" : {
          "enum": ["CONTAINS", "OVERLAPS", "EQUALS", "WITHIN", "CROSSES", "OTHERS"]
        },
        "comment" : {"type": "string"}
      },
      "required": ["featureType","connectedLayers","typeOfTopoExpression"]
    },

    "ExternalReference": {
      "$anchor": "ExternalReference",
      "type": "object",
      "properties": {
        "externalObject": {
          "type": "object",
          "properties": {
            "name": { "type": "string" },
            "uri": { "type": "string", "format": "uri" }
          },
          "required": ["name","uri"]
        },
        "informationSystem": { "type": "string", "format": "uri" }
      },
      "required": ["externalObject", "informationSystem"]
    }
  },

  "$ref": "#/$defs/IndoorFeatures"
}

=== opengeospatial/IndoorGML-SWG/IndoorGML2/IndoorGML2_metanorma/Part II/JSON/examples/indoorjson2_dummy.json
{
  "id": "IFs",
  "featureType": "IndoorFeatures",
  "layers": [
    {
      "id": "TL-1",
      "featureType": "ThematicLayer",
      "semanticExtension": false,
      "theme": "Physical",
      "primalSpace": {
        "id": "PS-1",
        "featureType": "PrimalSpaceLayer",
        "creationDatetime": "2025-10-30T13:00:00",
        "cellSpaceMember": [
          {
            "id": "R1",
            "featureType": "CellSpace",
            "duality": "N1",
            "poi": false,
            "level": "1",
            "cellSpaceGeom": {
              "geometry2D": {
                "type": "Polygon",
                "coordinates": [[[0,0], [3,0], [3,3], [0,3], [0,0]]]
              }
            },
            "boundedBy": ["B1"]
          },
          {
            "id": "R2",
            "featureType": "CellSpace",
            "duality": "N2",
            "poi": false,
            "level": "1",
            "cellSpaceGeom": {
              "geometry2D": {
                "type": "Polygon",
                "coordinates": [[[4,0], [7,0], [7,7], [4,7], [4,0]]]
              }
            },
            "boundedBy": ["B2"]
          },
          {
            "id": "D1",
            "featureType": "CellSpace",
            "duality": "N3",
            "poi": false,
            "level": "1",
            "cellSpaceGeom": {
              "geometry2D": {
                "type": "Polygon",
                "coordinates": [[[3,1], [4,1], [4,2], [3,2], [3,1]]]
              }
            },
            "boundedBy": ["B1", "B2"]
          }
        ],
        "cellBoundaryMember": [
          {
            "id": "B1",
            "featureType": "CellBoundary",
            "isVirtual": false,
            "duality": "E1",
            "cellBoundaryGeom": {
              "geometry2D": {
                "type": "LineString",
                "coordinates": [[3,1],[3,2]]
              }
            }
          },
          {
            "id": "B2",
            "featureType": "CellBoundary",
            "isVirtual": false,
            "duality": "E2",
            "cellBoundaryGeom": {
              "geometry2D": {
                "type": "LineString",
                "coordinates": [[4,1],[4,2]]
              }
            }
          }
        ]
      },
      "dualSpace": {
        "id": "DS-1",
        "featureType": "DualSpaceLayer",
        "creationDatetime": "2025-10-30T13:00:00",
        "isLogical": false,
        "isDirected": false,
        "nodeMember": [
          {
            "id": "N1",
            "featureType": "Node",
            "duality": "R1",
            "geometry": {
              "type": "Point",
              "coordinates": [1.5,1.5]
            },
            "connects": ["E1"]
          },
          {
            "id": "N2",
            "featureType": "Node",
            "duality": "R2",
            "geometry": {
              "type": "Point",
              "coordinates": [5.5,1.5]
            },
            "connects": ["E2"]
          },
          {
            "id": "N3",
            "featureType": "Node",
            "duality": "D1",
            "geometry": {
              "type": "Point",
              "coordinates": [3.5,1.5]
            },
            "connects": ["E1", "E2"]
          }
        ],
        "edgeMember": [
          {
            "id": "E1",
            "featureType": "Edge",
            "duality": "B1",
            "weight": 1.0,
            "geometry": {
              "type": "LineString",
              "coordinates": [[1.5,1.5],[3.5,1.5]]
            },
            "connects": ["N1", "N2"]
          },
          {
            "id": "E2",
            "featureType": "Edge",
            "duality": "B2",
            "weight": 1.0,
            "geometry": {
              "type": "LineString",
              "coordinates": [[3.5,1.5],[5.5,1.5]]
            },
            "connects": ["N2", "N3"]
          }
        ]
      }
    },
    {
      "id": "TL-2",
      "featureType": "ThematicLayer",
      "semanticExtension": false,
      "theme": "Physical",
      "primalSpace": {
        "id": "PS-2",
        "featureType": "PrimalSpaceLayer",
        "creationDatetime": "2025-10-30T13:00:00",
        "cellSpaceMember": [
          {
            "id": "P1",
            "featureType": "CellSpace",
            "duality": "PN1",
            "poi": true,
            "level": "1",
            "cellSpaceGeom": {
              "geometry2D": {
                "type": "Polygon",
                "coordinates": [[[0,0], [1,0], [1,1], [0,1], [0,0]]]
              }
            }
          }
        ]
      },
      "dualSpace": {
        "id": "DS-2",
        "featureType": "DualSpaceLayer",
        "creationDatetime": "2025-10-30T13:00:00",
        "isLogical": false,
        "isDirected": false,
        "nodeMember": [
          {
            "id": "PN1",
            "featureType": "Node",
            "duality": "P1",
            "geometry": {
              "type": "Point",
              "coordinates": [0.5,0.5]
            }
          }
        ]
      }
    }
  ],
  "layerConnections": [
    {
      "id": "ILC-1",
      "featureType": "InterLayerConnection",
      "connectedLayers": ["TL-1", "TL-2"],
      "connectedNodes": ["N1", "PN1"],
      "connectedCells": ["R1", "P1"],
      "typeOfTopoExpression": "CONTAINS"
    }
  ]
}
